# Form implementation generated from reading ui file 'student_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentForm(object):
    def setupUi(self, StudentForm):
        StudentForm.setObjectName("StudentForm")
        StudentForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        StudentForm.resize(417, 259)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(StudentForm)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_login = QtWidgets.QLabel(parent=StudentForm)
        self.lbl_login.setObjectName("lbl_login")
        self.verticalLayout.addWidget(self.lbl_login)
        self.edt_login = QtWidgets.QLineEdit(parent=StudentForm)
        self.edt_login.setObjectName("edt_login")
        self.verticalLayout.addWidget(self.edt_login)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_fio = QtWidgets.QLabel(parent=StudentForm)
        self.lbl_fio.setObjectName("lbl_fio")
        self.verticalLayout_2.addWidget(self.lbl_fio)
        self.edt_fio = QtWidgets.QLineEdit(parent=StudentForm)
        self.edt_fio.setObjectName("edt_fio")
        self.verticalLayout_2.addWidget(self.edt_fio)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_email = QtWidgets.QLabel(parent=StudentForm)
        self.lbl_email.setObjectName("lbl_email")
        self.verticalLayout_3.addWidget(self.lbl_email)
        self.edt_email = QtWidgets.QLineEdit(parent=StudentForm)
        self.edt_email.setObjectName("edt_email")
        self.verticalLayout_3.addWidget(self.edt_email)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_comment = QtWidgets.QLabel(parent=StudentForm)
        self.lbl_comment.setObjectName("lbl_comment")
        self.verticalLayout_4.addWidget(self.lbl_comment)
        self.edt_comment = QtWidgets.QTextEdit(parent=StudentForm)
        self.edt_comment.setObjectName("edt_comment")
        self.verticalLayout_4.addWidget(self.edt_comment)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(StudentForm)
        QtCore.QMetaObject.connectSlotsByName(StudentForm)

    def retranslateUi(self, StudentForm):
        _translate = QtCore.QCoreApplication.translate
        StudentForm.setWindowTitle(_translate("StudentForm", "Form"))
        self.lbl_login.setText(_translate("StudentForm", "Login"))
        self.lbl_fio.setText(_translate("StudentForm", "Fullname N. P."))
        self.lbl_email.setText(_translate("StudentForm", "email"))
        self.lbl_comment.setText(_translate("StudentForm", "Comment"))
