# Form implementation generated from reading ui file 'teacher_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TeacherForm(object):
    def setupUi(self, TeacherForm):
        TeacherForm.setObjectName("TeacherForm")
        TeacherForm.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        TeacherForm.resize(440, 224)
        self.verticalLayout = QtWidgets.QVBoxLayout(TeacherForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lay_line1 = QtWidgets.QHBoxLayout()
        self.lay_line1.setObjectName("lay_line1")
        self.lay_login = QtWidgets.QVBoxLayout()
        self.lay_login.setSpacing(0)
        self.lay_login.setObjectName("lay_login")
        self.lbl_login = QtWidgets.QLabel(parent=TeacherForm)
        self.lbl_login.setObjectName("lbl_login")
        self.lay_login.addWidget(self.lbl_login)
        self.edt_login = QtWidgets.QLineEdit(parent=TeacherForm)
        self.edt_login.setObjectName("edt_login")
        self.lay_login.addWidget(self.edt_login)
        self.lay_line1.addLayout(self.lay_login)
        self.lay_fio = QtWidgets.QVBoxLayout()
        self.lay_fio.setSpacing(0)
        self.lay_fio.setObjectName("lay_fio")
        self.lbl_fio = QtWidgets.QLabel(parent=TeacherForm)
        self.lbl_fio.setObjectName("lbl_fio")
        self.lay_fio.addWidget(self.lbl_fio)
        self.edt_fio = QtWidgets.QLineEdit(parent=TeacherForm)
        self.edt_fio.setObjectName("edt_fio")
        self.lay_fio.addWidget(self.edt_fio)
        self.lay_line1.addLayout(self.lay_fio)
        self.lay_line1.setStretch(0, 1)
        self.lay_line1.setStretch(1, 2)
        self.verticalLayout.addLayout(self.lay_line1)
        self.lay_line2 = QtWidgets.QHBoxLayout()
        self.lay_line2.setObjectName("lay_line2")
        self.lay_phone = QtWidgets.QVBoxLayout()
        self.lay_phone.setSpacing(0)
        self.lay_phone.setObjectName("lay_phone")
        self.lbl_phone = QtWidgets.QLabel(parent=TeacherForm)
        self.lbl_phone.setObjectName("lbl_phone")
        self.lay_phone.addWidget(self.lbl_phone)
        self.edt_phone = QtWidgets.QLineEdit(parent=TeacherForm)
        self.edt_phone.setObjectName("edt_phone")
        self.lay_phone.addWidget(self.edt_phone)
        self.lay_line2.addLayout(self.lay_phone)
        self.lay_email = QtWidgets.QVBoxLayout()
        self.lay_email.setSpacing(0)
        self.lay_email.setObjectName("lay_email")
        self.lbl_email = QtWidgets.QLabel(parent=TeacherForm)
        self.lbl_email.setObjectName("lbl_email")
        self.lay_email.addWidget(self.lbl_email)
        self.edt_email = QtWidgets.QLineEdit(parent=TeacherForm)
        self.edt_email.setObjectName("edt_email")
        self.lay_email.addWidget(self.edt_email)
        self.lay_line2.addLayout(self.lay_email)
        self.verticalLayout.addLayout(self.lay_line2)
        self.lay_comment = QtWidgets.QVBoxLayout()
        self.lay_comment.setSpacing(0)
        self.lay_comment.setObjectName("lay_comment")
        self.lbl_comment = QtWidgets.QLabel(parent=TeacherForm)
        self.lbl_comment.setObjectName("lbl_comment")
        self.lay_comment.addWidget(self.lbl_comment)
        self.edt_comment = QtWidgets.QTextEdit(parent=TeacherForm)
        self.edt_comment.setObjectName("edt_comment")
        self.lay_comment.addWidget(self.edt_comment)
        self.verticalLayout.addLayout(self.lay_comment)

        self.retranslateUi(TeacherForm)
        QtCore.QMetaObject.connectSlotsByName(TeacherForm)

    def retranslateUi(self, TeacherForm):
        _translate = QtCore.QCoreApplication.translate
        TeacherForm.setWindowTitle(_translate("TeacherForm", "Form"))
        self.lbl_login.setText(_translate("TeacherForm", "Login"))
        self.lbl_fio.setText(_translate("TeacherForm", "Fullname N. P."))
        self.lbl_phone.setText(_translate("TeacherForm", "phone"))
        self.lbl_email.setText(_translate("TeacherForm", "email"))
        self.lbl_comment.setText(_translate("TeacherForm", "Comment"))
